// Slice 710 — DXF 3D entity exporter. AutoCAD DXF supports
// 3DFACE / POLYLINE-with-VERTEX-3D / 3DSOLID-via-ACIS-blob. We emit
// 3DFACE for every triangle and group meshes by LAYER for usable
// 3D import into AutoCAD / BricsCAD / DraftSight.

import * as THREE from 'three';

function _dxfHeader() {
  return [
    '0', 'SECTION', '2', 'HEADER',
    '9', '$ACADVER', '1', 'AC1027',   // AutoCAD 2013 format
    '9', '$INSBASE', '10', '0.0', '20', '0.0', '30', '0.0',
    '9', '$EXTMIN', '10', '-1000', '20', '-1000', '30', '-1000',
    '9', '$EXTMAX', '10', '1000', '20', '1000', '30', '1000',
    '0', 'ENDSEC',
  ].join('\n');
}

function _dxfTablesSection(layerNames) {
  const lines = ['0', 'SECTION', '2', 'TABLES', '0', 'TABLE', '2', 'LAYER',
    '70', String(layerNames.length)];
  let colorCycle = 1;
  for (const name of layerNames) {
    lines.push(
      '0', 'LAYER',
      '2', name,
      '70', '0',
      '62', String(colorCycle),
      '6', 'CONTINUOUS',
    );
    colorCycle = colorCycle % 250 + 1;
  }
  lines.push('0', 'ENDTAB', '0', 'ENDSEC');
  return lines.join('\n');
}

function _dxfEntitiesSection(meshes) {
  const lines = ['0', 'SECTION', '2', 'ENTITIES'];
  for (const m of meshes) {
    const layer = m.layer || 'STUDIO';
    const geo = m.mesh.geometry;
    if (!geo?.attributes?.position) continue;
    const pos = geo.attributes.position.array;
    const idx = geo.index?.array;
    const triCount = idx ? idx.length / 3 : pos.length / 9;
    m.mesh.updateMatrixWorld(true);
    const mat = m.mesh.matrixWorld;
    for (let t = 0; t < triCount; t++) {
      const i0 = idx ? idx[t * 3] : t * 3;
      const i1 = idx ? idx[t * 3 + 1] : t * 3 + 1;
      const i2 = idx ? idx[t * 3 + 2] : t * 3 + 2;
      const a = new THREE.Vector3(pos[i0 * 3], pos[i0 * 3 + 1], pos[i0 * 3 + 2]).applyMatrix4(mat);
      const b = new THREE.Vector3(pos[i1 * 3], pos[i1 * 3 + 1], pos[i1 * 3 + 2]).applyMatrix4(mat);
      const c = new THREE.Vector3(pos[i2 * 3], pos[i2 * 3 + 1], pos[i2 * 3 + 2]).applyMatrix4(mat);
      lines.push(
        '0', '3DFACE',
        '8', layer,
        '10', a.x.toFixed(6), '20', a.y.toFixed(6), '30', a.z.toFixed(6),
        '11', b.x.toFixed(6), '21', b.y.toFixed(6), '31', b.z.toFixed(6),
        '12', c.x.toFixed(6), '22', c.y.toFixed(6), '32', c.z.toFixed(6),
        '13', c.x.toFixed(6), '23', c.y.toFixed(6), '33', c.z.toFixed(6),
      );
    }
  }
  lines.push('0', 'ENDSEC');
  return lines.join('\n');
}

function _dxfFooter() { return ['0', 'EOF'].join('\n'); }

export function exportScene3D(opts) {
  const scene = window.__archdiscScene;
  if (!scene) return { ok: false };
  const meshes = [];
  const layerSet = new Set();
  scene.traverseVisible((o) => {
    if (!o.isMesh) return;
    const layer = (o.userData?.archdiscLayer || o.name || 'STUDIO').replace(/[^A-Z0-9_-]/gi, '_');
    layerSet.add(layer);
    meshes.push({ mesh: o, layer });
  });
  if (layerSet.size === 0) layerSet.add('STUDIO');
  const dxf = [
    _dxfHeader(),
    _dxfTablesSection(Array.from(layerSet)),
    _dxfEntitiesSection(meshes),
    _dxfFooter(),
  ].join('\n');
  if (opts?.download !== false) {
    const blob = new Blob([dxf], { type: 'application/dxf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = opts?.filename || 'studio.dxf';
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  }
  return { ok: true, source: dxf, layers: Array.from(layerSet), tris: meshes.reduce((acc, m) => {
    const idx = m.mesh.geometry.index?.array;
    const pos = m.mesh.geometry.attributes.position.array;
    return acc + (idx ? idx.length / 3 : pos.length / 9);
  }, 0) };
}

// Paper-space layout — export a 2D top + front + side + iso view to a
// single DXF as separate viewports.
export function exportPaperSpaceLayout(opts) {
  const viewport = window.__archdiscViewport;
  if (!viewport?.renderer) return { ok: false };
  const views = ['top', 'front', 'side', 'iso'];
  const exports = {};
  for (const v of views) {
    exports[v] = `; viewport: ${v}\n`;
  }
  // For now just emit the same 3D scene with a comment for the layout
  // metadata; full layout requires DXF block + viewport setup.
  const scene3D = exportScene3D({ download: false });
  const composite = [
    '; Paper-Space Layout — 4 viewports',
    '; Generated by ArchDisc Studio',
    scene3D.source,
  ].join('\n');
  if (opts?.download !== false) {
    const blob = new Blob([composite], { type: 'application/dxf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = opts?.filename || 'studio-paperspace.dxf';
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  }
  return { ok: true, source: composite };
}
