#!/usr/bin/env node
/*
 * One-shot generator — parses the Utah teapot + color-cube X3D fixtures
 * shipped in blender/tests/files/io_tests/x3d/ and emits deterministic
 * JS modules with vertex + index typed arrays.
 *
 * Mirrors tools/import_suzanne.py (Python). Studio now imports
 * `TeapotGeometry.js` + `ColorCubeGeometry.js` and renders them as
 * first-class primitives just like Suzanne.
 */
const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const SRC_DIR   = path.join(REPO_ROOT, 'blender', 'tests', 'files', 'io_tests', 'x3d');
const OUT_DIR   = path.join(REPO_ROOT, 'frontend', 'src', 'workbenches', 'studio');

function parseCoordIndex(raw) {
  // X3D coordIndex is whitespace-separated ints; -1 ends each polygon.
  const faces = [];
  let cur = [];
  for (const tok of raw.replace(/,/g, ' ').split(/\s+/)) {
    if (!tok) continue;
    const v = parseInt(tok, 10);
    if (isNaN(v)) continue;
    if (v === -1) {
      if (cur.length) { faces.push(cur); cur = []; }
    } else {
      cur.push(v);
    }
  }
  if (cur.length) faces.push(cur);
  return faces;
}

function parsePoints(raw) {
  // X3D points: space-separated triples optionally separated by commas.
  const tokens = raw.replace(/,/g, ' ').split(/\s+/).filter(Boolean);
  const pts = [];
  for (let i = 0; i + 2 < tokens.length; i += 3) {
    pts.push([
      parseFloat(tokens[i]),
      parseFloat(tokens[i + 1]),
      parseFloat(tokens[i + 2]),
    ]);
  }
  return pts;
}

function centerAndScale(points, extentMm) {
  if (points.length === 0) return points;
  let minX = +Infinity, minY = +Infinity, minZ = +Infinity;
  let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
  for (const [x, y, z] of points) {
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
    if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
  }
  const cx = (minX + maxX) / 2;
  const cy = (minY + maxY) / 2;
  const cz = (minZ + maxZ) / 2;
  const ex = maxX - minX;
  const ey = maxY - minY;
  const ez = maxZ - minZ;
  const maxExt = Math.max(ex, ey, ez) || 1;
  const scale = extentMm / maxExt;
  return points.map(([x, y, z]) => [
    (x - cx) * scale,
    (y - cy) * scale,
    (z - cz) * scale,
  ]);
}

function triangulateFanFromZero(faces) {
  const tris = [];
  for (const face of faces) {
    if (face.length < 3) continue;
    for (let i = 1; i < face.length - 1; i++) {
      tris.push(face[0], face[i], face[i + 1]);
    }
  }
  return tris;
}

function emitJsModule(outPath, modName, points, indices) {
  const lines = [];
  lines.push('/* Auto-generated by tools/import_teapot_and_colorcube.js — DO NOT EDIT.');
  lines.push(' * Source: blender/tests/files/io_tests/x3d/.');
  lines.push(' * Triangulated + centred + scaled to fit Studio\'s mm-scale camera.');
  lines.push(' */');
  lines.push('');
  lines.push(`export const ${modName}_POSITIONS = new Float32Array([`);
  const xs = [];
  for (const [x, y, z] of points) xs.push(x.toFixed(6), y.toFixed(6), z.toFixed(6));
  for (let i = 0; i < xs.length; i += 9) {
    lines.push('  ' + xs.slice(i, i + 9).join(', ') + ',');
  }
  lines.push(']);');
  lines.push('');
  const arrType = (points.length - 1) > 65535 ? 'Uint32Array' : 'Uint16Array';
  lines.push(`export const ${modName}_INDICES = new ${arrType}([`);
  for (let i = 0; i < indices.length; i += 24) {
    lines.push('  ' + indices.slice(i, i + 24).join(', ') + ',');
  }
  lines.push(']);');
  lines.push('');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
}

function processOne(srcFile, outFile, modName, extentMm) {
  const text = fs.readFileSync(srcFile, 'utf8');
  const coordIdxMatches = [...text.matchAll(/coordIndex='([^']+)'|coordIndex="([^"]+)"/g)];
  const pointMatches    = [...text.matchAll(/point='([^']+)'|point="([^"]+)"/g)];
  if (coordIdxMatches.length === 0 || pointMatches.length === 0) {
    console.error(`[err] no coordIndex / point in ${srcFile}`);
    return;
  }
  // Pick the LONGEST match — these fixtures may have nested geometries.
  let longestIdx = '', longestPts = '';
  for (const m of coordIdxMatches) {
    const v = m[1] || m[2];
    if (v && v.length > longestIdx.length) longestIdx = v;
  }
  for (const m of pointMatches) {
    const v = m[1] || m[2];
    if (v && v.length > longestPts.length) longestPts = v;
  }
  const faces  = parseCoordIndex(longestIdx);
  const points = parsePoints(longestPts);
  const centered = centerAndScale(points, extentMm);
  const indices  = triangulateFanFromZero(faces);
  console.log(`[ok] ${path.basename(srcFile)}: ${points.length} verts, ${faces.length} polys -> ${indices.length / 3} tris`);
  emitJsModule(outFile, modName, centered, indices);
}

processOne(
  path.join(SRC_DIR, 'teapot.x3d'),
  path.join(OUT_DIR, 'TeapotGeometry.js'),
  'TEAPOT',
  0.04, // 40 mm
);

processOne(
  path.join(SRC_DIR, 'color_cube.x3d'),
  path.join(OUT_DIR, 'ColorCubeGeometry.js'),
  'COLOR_CUBE',
  0.03, // 30 mm
);
