"""Convert blender/.../suzanne_material.x3d → frontend/.../SuzanneGeometry.js.

One-shot. Reads Suzanne's X3D IndexedFaceSet from the vendored Blender
tests dir, extracts vertex positions + face indices, triangulates any
quads/n-gons, writes a deterministic JS module exporting the data as
typed arrays. Studio imports the module and builds a BufferGeometry
from the static tables — first Studio primitive whose geometry is
literally imported from blender/.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_X3D = REPO_ROOT / "blender" / "tests" / "files" / "io_tests" / "x3d" / "suzanne_material.x3d"
OUT_JS = REPO_ROOT / "frontend" / "src" / "workbenches" / "studio" / "SuzanneGeometry.js"


def parse_coord_index(s: str) -> list[list[int]]:
    """X3D coordIndex is space-separated ints; -1 ends each face."""
    faces: list[list[int]] = []
    cur: list[int] = []
    for tok in s.replace(",", " ").split():
        try:
            v = int(tok)
        except ValueError:
            continue
        if v == -1:
            if cur:
                faces.append(cur)
                cur = []
        else:
            cur.append(v)
    if cur:
        faces.append(cur)
    return faces


def parse_point(s: str) -> list[tuple[float, float, float]]:
    """X3D point list — comma-separated triples like 'x y z, x y z, ...'."""
    pts: list[tuple[float, float, float]] = []
    for chunk in s.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        nums = chunk.split()
        if len(nums) >= 3:
            pts.append((float(nums[0]), float(nums[1]), float(nums[2])))
    return pts


def main() -> int:
    if not SRC_X3D.exists():
        print(f"[err] x3d not found: {SRC_X3D}", file=sys.stderr)
        return 1
    text = SRC_X3D.read_text(encoding="utf-8")
    # Several Shape blocks exist (Plane, then Suzanne). Find the one
    # that contains many faces — Suzanne has 500 faces; the Plane has 1.
    # The largest coordIndex/point pair wins.
    coord_idx_matches = list(re.finditer(r'coordIndex="([^"]+)"', text))
    point_matches = list(re.finditer(r'point="([^"]+)"', text))
    if not coord_idx_matches or not point_matches:
        print("[err] no coordIndex / point attribute in x3d", file=sys.stderr)
        return 2
    # The Plane (4 verts) and Monkey (505 verts) both have <Coordinate>
    # DEF nodes with point="..." attributes. Pick the LONGEST point list
    # (Monkey) and the LONGEST coordIndex (also Monkey) — both are the
    # max in their respective attributes, so plucking the longest of
    # each is robust to ordering.
    longest_idx_m = max(coord_idx_matches, key=lambda m: len(m.group(1)))
    faces = parse_coord_index(longest_idx_m.group(1))
    longest_pt_m = max(point_matches, key=lambda m: len(m.group(1)))
    points = parse_point(longest_pt_m.group(1))

    print(f"[info] Suzanne: {len(points)} vertices, {len(faces)} polygons (pre-triangulate)")

    # Triangulate: for each face with N corners, emit N-2 triangles using
    # a fan from vertex 0.
    tri_indices: list[int] = []
    for f in faces:
        if len(f) < 3:
            continue
        for i in range(1, len(f) - 1):
            tri_indices.extend([f[0], f[i], f[i + 1]])
    print(f"[info] triangulated: {len(tri_indices) // 3} triangles")

    # Center the mesh on its bounding-box center so addPrimitive's grid
    # layout doesn't offset it weirdly.
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    zs = [p[2] for p in points]
    cx = (min(xs) + max(xs)) / 2
    cy = (min(ys) + max(ys)) / 2
    cz = (min(zs) + max(zs)) / 2
    points = [(p[0] - cx, p[1] - cy, p[2] - cz) for p in points]

    # Scale so the model fits roughly Studio's PRIMITIVE_SIZE (30 mm).
    diag = max(max(xs) - min(xs), max(ys) - min(ys), max(zs) - min(zs))
    target_extent = 0.03  # 30 mm
    scale = target_extent / diag if diag > 0 else 1.0
    points = [(p[0] * scale, p[1] * scale, p[2] * scale) for p in points]
    print(f"[info] auto-scaled by {scale:.5f}× to fit ~30 mm extent")

    # Emit JS module — static Float32Array + Uint16Array literals.
    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    with OUT_JS.open("w", encoding="utf-8") as f:
        f.write("/*\n")
        f.write(" * Suzanne — Blender's iconic monkey primitive.\n")
        f.write(" *\n")
        f.write(" * Source: blender/tests/files/io_tests/x3d/suzanne_material.x3d\n")
        f.write(" * License: Blender source is GPL-3.0-or-later (matches Studio's license).\n")
        f.write(" *\n")
        f.write(" * Generated by tools/import_suzanne.py — do not edit by hand. Re-run\n")
        f.write(" * the importer to refresh if the upstream Blender x3d test data changes.\n")
        f.write(" *\n")
        f.write(f" * {len(points)} vertices, {len(tri_indices)//3} triangles (triangulated from\n")
        f.write(f" * {len(faces)} polygons via fan triangulation).\n")
        f.write(" */\n\n")
        f.write("export const SUZANNE_POSITIONS = new Float32Array([\n")
        for i, (x, y, z) in enumerate(points):
            f.write(f"  {x:.6f}, {y:.6f}, {z:.6f},")
            f.write("\n" if (i + 1) % 4 == 0 else " ")
        if len(points) % 4 != 0:
            f.write("\n")
        f.write("]);\n\n")
        # Choose index array type by max index.
        max_idx = max(tri_indices) if tri_indices else 0
        arr_type = "Uint16Array" if max_idx < 65536 else "Uint32Array"
        f.write(f"export const SUZANNE_INDICES = new {arr_type}([\n")
        for i in range(0, len(tri_indices), 9):
            f.write("  " + ", ".join(str(x) for x in tri_indices[i:i + 9]) + ",\n")
        f.write("]);\n")
    print(f"[done] wrote {OUT_JS} ({OUT_JS.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
